name: buzing_crowd_detection
description: "Buzing.lk — Bus Doorway Crowd Counter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.1
  image: ^4.3.0
  camera: ^0.11.0+2
  video_thumbnail: ^0.5.3
  file_picker: ^8.1.7
  video_player: ^2.9.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  intl: ^0.19.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/best.tflite
